# Generated by Django 2.2.1 on 2019-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
